# Generated by Django 4.0.6 on 2022-07-16 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_management",
            "0004_remove_locationforworking_number_employee_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyCalendarFromLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date_week", models.DateField(null=True)),
                ("mond_hour", models.IntegerField(default=0, null=True)),
                (
                    "location_place",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management.locationforworking",
                    ),
                ),
                (
                    "specific_employee",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management.employeebaseinformation",
                    ),
                ),
            ],
        ),
    ]
