# Generated by Django 4.0.6 on 2022-07-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0005_weeklycalendarfromlocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklycalendarfromlocation", name="mond_hour",
        ),
        migrations.RemoveField(
            model_name="weeklycalendarfromlocation", name="specific_employee",
        ),
    ]
