# Generated by Django 4.0.4 on 2022-07-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0007_hoursworkedfromweeklycalendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationforworking",
            name="notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
