# Generated by Django 4.0.6 on 2022-07-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0008_alter_locationforworking_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyHoursForEachEmployeeAndLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_hours", models.IntegerField(null=True)),
                (
                    "specific_employee_working",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management.employeebaseinformation",
                    ),
                ),
                (
                    "specific_weekly_calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management.weeklycalendarfromlocation",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HoursWorkedFromWeeklyCalendar",
        ),
    ]
