# Generated by Django 4.0.6 on 2022-07-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_management",
            "0010_rename_num_hours_weeklyhoursforeachemployeeandlocation_monday_num_hours_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
