# Generated by Django 4.0.6 on 2022-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0011_generalnotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalnotes",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
