# Generated by Django 4.0.6 on 2022-08-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0015_locationforworkingclone"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeBaseInformationClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.IntegerField(null=True)),
                ("start_date", models.DateField(null=True)),
                ("salary", models.IntegerField(null=True)),
                ("bonus", models.IntegerField(null=True)),
                ("is_driver", models.BooleanField(null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("custom_id", models.IntegerField(null=True)),
                (
                    "place",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management.locationforworking",
                    ),
                ),
            ],
        ),
    ]
