# Generated by Django 4.0.6 on 2022-08-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0016_employeebaseinformationclone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnotes',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyCalendarFromLocationClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_week', models.DateField(null=True)),
                ('custom_id', models.IntegerField(null=True)),
                ('location_place', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.locationforworking')),
            ],
        ),
    ]
