# Generated by Django 4.0.6 on 2022-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management_dev", "0002_locationforworking_number_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationforworking",
            name="number_employee",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
