# Generated by Django 4.0.4 on 2022-07-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_management_dev",
            "0006_remove_weeklycalendarfromlocation_mond_hour_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HoursWorkedFromWeeklyCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mon_hour", models.IntegerField(null=True)),
                (
                    "employee_selected",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management_dev.employeebaseinformation",
                    ),
                ),
                (
                    "weekly_calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management_dev.weeklycalendarfromlocation",
                    ),
                ),
            ],
        ),
    ]
