# Generated by Django 4.0.6 on 2022-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management_dev", "0009_weeklyhoursforeachemployeeandlocation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weeklyhoursforeachemployeeandlocation",
            old_name="num_hours",
            new_name="monday_num_hours",
        ),
        migrations.AddField(
            model_name="weeklyhoursforeachemployeeandlocation",
            name="friday_num_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weeklyhoursforeachemployeeandlocation",
            name="saturday_num_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weeklyhoursforeachemployeeandlocation",
            name="sunday_num_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weeklyhoursforeachemployeeandlocation",
            name="thursday_num_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weeklyhoursforeachemployeeandlocation",
            name="tuesday_num_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weeklyhoursforeachemployeeandlocation",
            name="wednesday_num_hours",
            field=models.IntegerField(null=True),
        ),
    ]
