# Generated by Django 4.0.6 on 2022-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_management_dev",
            "0014_alter_weeklyhoursforeachemployeeandlocation_friday_num_hours_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationForWorkingClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=100, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("custom_id", models.IntegerField(null=True)),
            ],
        ),
    ]
